FROM ubuntu:14.04
WORKDIR /app
SHELL ["/bin/bash", "-c"]

# Update APT and install some pre-requisites
RUN apt-get update && apt-get install -y apt-transport-https curl git

COPY *.sh scripts/
RUN chmod +x scripts/install_dotnetcore.sh && scripts/install_dotnetcore.sh
# Mono is not currently required in this image (it crashes paket so using nuget)
#RUN chmod +x scripts/install_mono.sh && scripts/install_mono.sh

# Clone the code and restore the packages
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_CLI_TELEMETRY_OPTOUT=1
RUN git clone https://github.com/garfoot/FluentUri.git fluenturi \
    && dotnet restore fluenturi

ENTRYPOINT [ "bash" ]
